# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'encryptionPass.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(401, 199)
        Dialog.setMaximumSize(QtCore.QSize(401, 251))
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 401, 251))
        self.frame.setMinimumSize(QtCore.QSize(401, 251))
        self.frame.setMaximumSize(QtCore.QSize(401, 251))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color:#292b2b;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setGeometry(QtCore.QRect(220, 160, 164, 32))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(160, 60, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.password.setFont(font)
        self.password.setStyleSheet("QLineEdit {\n"
"    border-radius:8px;\n"
"    background-color: white;\n"
"    color:black;\n"
"\n"
"}")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.confirm_password = QtWidgets.QLineEdit(self.frame)
        self.confirm_password.setGeometry(QtCore.QRect(160, 110, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.confirm_password.setFont(font)
        self.confirm_password.setStyleSheet("QLineEdit {\n"
"    border-radius:8px;\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.confirm_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_password.setObjectName("confirm_password")
        self.password_label = QtWidgets.QLabel(self.frame)
        self.password_label.setGeometry(QtCore.QRect(20, 70, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.password_label.setFont(font)
        self.password_label.setStyleSheet("QLabel {\n"
"    color:white;\n"
"}")
        self.password_label.setObjectName("password_label")
        self.confirm_passwordLabel = QtWidgets.QLabel(self.frame)
        self.confirm_passwordLabel.setGeometry(QtCore.QRect(20, 120, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.confirm_passwordLabel.setFont(font)
        self.confirm_passwordLabel.setStyleSheet("QLabel {\n"
"    color:white;\n"
"}")
        self.confirm_passwordLabel.setObjectName("confirm_passwordLabel")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(110, 10, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color:white;\n"
"}")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.close)
        Dialog.rejected.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.password_label.setText(_translate("Dialog", "Password"))
        self.confirm_passwordLabel.setText(_translate("Dialog", "Confrim Password"))
        self.label.setText(_translate("Dialog", "Set Password For Encryption "))
