# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fileEncryptor_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    borders:none;\n"
"    borders-radius:12px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color:rgb(151, 146, 193);\n"
"    borders:none;\n"
"    border-radius:12px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.dir_Screen = QtWidgets.QLabel(self.frame)
        self.dir_Screen.setGeometry(QtCore.QRect(110, 70, 541, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dir_Screen.sizePolicy().hasHeightForWidth())
        self.dir_Screen.setSizePolicy(sizePolicy)
        self.dir_Screen.setStyleSheet("QLabel{      \n"
"        background-color:rgb(234, 234, 234);\n"
"        color:black;\n"
"}")
        self.dir_Screen.setAlignment(QtCore.Qt.AlignCenter)
        self.dir_Screen.setObjectName("dir_Screen")
        self.browse_btn = QtWidgets.QPushButton(self.frame)
        self.browse_btn.setGeometry(QtCore.QRect(670, 70, 61, 31))
        self.browse_btn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(63, 63, 63);\n"
"    color:rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(124, 124, 124);\n"
"\n"
"}\n"
"")
        self.browse_btn.setObjectName("browse_btn")
        self.file_Screen = QtWidgets.QLabel(self.frame)
        self.file_Screen.setGeometry(QtCore.QRect(110, 130, 541, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_Screen.sizePolicy().hasHeightForWidth())
        self.file_Screen.setSizePolicy(sizePolicy)
        self.file_Screen.setStyleSheet("QLabel{      \n"
"        background-color:rgb(234, 234, 234);\n"
"        color:black;\n"
"}")
        self.file_Screen.setAlignment(QtCore.Qt.AlignCenter)
        self.file_Screen.setObjectName("file_Screen")
        self.browse_btn_3 = QtWidgets.QPushButton(self.frame)
        self.browse_btn_3.setGeometry(QtCore.QRect(70, 470, 91, 41))
        self.browse_btn_3.setStyleSheet("QPushButton {\n"
"    background-color:rgb(63, 63, 63);\n"
"    color:rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(124, 124, 124);\n"
"\n"
"}")
        self.browse_btn_3.setObjectName("browse_btn_3")
        self.browse_btn_4 = QtWidgets.QPushButton(self.frame)
        self.browse_btn_4.setGeometry(QtCore.QRect(600, 470, 91, 41))
        self.browse_btn_4.setStyleSheet("QPushButton {\n"
"    background-color:rgb(63, 63, 63);\n"
"    color:rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(124, 124, 124);\n"
"\n"
"}")
        self.browse_btn_4.setObjectName("browse_btn_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 20, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Tamil Sangam MN")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color:rgb(234, 234, 234)\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dir_Screen.setText(_translate("MainWindow", "File Directory"))
        self.browse_btn.setText(_translate("MainWindow", "Browse"))
        self.file_Screen.setText(_translate("MainWindow", "File Viewer"))
        self.browse_btn_3.setText(_translate("MainWindow", "Encrypt"))
        self.browse_btn_4.setText(_translate("MainWindow", "Decrypt"))
        self.label.setText(_translate("MainWindow", "File Encryptor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
